### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by UjwalBattar** [UjwalBattar/LairBnB#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
## Functionality

- [x] add default image for new users
- [x] https://lair-b-n-b.herokuapp.com/#/ierugbiewurgb should be a redirect or 404 page

## Styling

- [x] Add spacing to nav buttons, make them the same
